<?php

namespace Application\Repositorio;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository {

    public function doSave($objQuestion = null, $arrDados = []) {

        try {
            $objQuiz = $this->getEntityManager()
                ->getRepository(\Application\Entidade\Quiz::class)
                ->findOneBy(
                    array(
                        'id' => $arrDados['id'],
                    )
                );
            $objType = $this->getEntityManager()
                ->getRepository(\Application\Entidade\TypeQuestion::class)
                ->findOneBy(
                    array(
                        'id' => $arrDados['type_id'],
                    )
                );

            if (empty($objQuestion)) {
                $objQuestion = new Question();

                $arrDados['create_at'] = date('Y-m-d H:i:s');
            }

            $objQuestion->setSubject($arrDados['subject']);
            $objQuestion->setCreatedAt($arrDados['create_at']);
            $objQuestion->setUpdatedAt(date('Y-m-d H:i'));
            $objQuestion->setQuiz($objQuiz);
            $objQuestion->setType($objType);

            $this->getEntityManager()
                ->persist($objUlmsChatSala);

            $this->getEntityManager()
                ->flush();

        } catch (\Exception $objException) {

            throw new \Exception($objException->getMessage(), 10);

        }

    }
}
