<?
    $this->inlineScript()
        ->appendFile($this->basePath('js/controller/admin/index.js'));

?>
<section ng-app="AppAngular" ng-controller="adminQuizController">

    <div class="row">

        <div class="col-md-8">
        <h1>Lista de fórum</h1>

            <table class="table table-bordered">
                <thead>
                    <th>#ID</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th></th>
                </thead>

                <tbody ng-repeat="(key, value) in arrQuiz">
                    <tr>
                        <td>
                            {{value.id}}
                        </td>
                        <td>
                            {{value.name}}
                        </td>
                        <td>
                            {{value.description}}
                        </td>
                        <td>
                            <button class="btn btn-sm btn-primary" ng-click="setEdit(value)">Editar</button>
                            <a href="/admin/option/{{value.id}}" class="btn btn-sm btn-warning">Opções</a>
                            <button class="btn btn-sm btn-success">Participações</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <a class="btn btn-primary" data-toggle="modal" href='#formQuiz'>Criar novo quiz</a>
    <div class="modal fade" id="formQuiz">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Cadastrar novo quiz</h4>
                </div>
                <div class="modal-body">


                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label>Nome</label>
                                <input type="text" ng-model="objQuiz.name" class="form-control" name="">
                            </div>

                            <div class="form-group">
                                <label>Descrição</label>
                                <textarea ng-model="objQuiz.description" class="form-control" name=""></textarea>
                            </div>

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" ng-click="clearForm()">Sair</button>
                    <button type="button" class="btn btn-primary" ng-click="saveQuiz()">Salvar</button>
                </div>
            </div>
        </div>
    </div>

</section>