<?
    $this->inlineScript()
        ->appendFile($this->basePath('js/controller/admin/question.js'));

?>
<section ng-app="AppAngular" ng-controller="adminQuizController">

    <?php foreach($arrTypes as $arrType): ?>
    <span ng-init="setArrType('<?php echo $arrType['name'];?>',<?php echo $arrType['id'];?>)"/>
    <?php endforeach;?>
    <span ng-init="question_id = <?php echo $arrType['id'];?>"/>
    <span ng-init="loadQuestion()"/>

    <div class="row-fluid">
        <div class="col-md-6">
            <form action="" method="POST" role="form">
                <legend>Question</legend>

                <div class="form-group">
                    <label for="">Subject</label>
                    <textarea
                        type="text"
                        class="form-control"
                        id=""
                        ng-model="formQuestion.subject"
                        placeholder="Subject"
                        rows="8">
                    </textarea>
                </div>

                <div class="form-group">
                    <label for="">Type</label>

                    <select
                        ng-model="formQuestion.type_id"
                        class="form-control"
                        id=""
                        ng-options="value.id as value.name for value in arrType">

                    </select>
                </div>



                <button type="button" class="btn btn-primary" ng-click="saveQuestion()">Save</button>
                <button type="button" class="btn btn-warning">Clear</button>
            </form>
        </div>
    </div>


    <div class="row-fluid">
        <div class="col-md-12">
            <h3>Questions</h3>
            <table class="table table-bordered">
                <thead>
                    <th>#</th>
                    <th>Subject</th>
                    <th>Type</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    <tr ng-repeat="(key, value) in arrQuestion">
                        <td>{{value.id}}</td>
                        <td>{{value.subject}}</td>
                        <td>{{value.type_description}}</td>
                        <td>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>